### PR TITLE
merge Debian package into main git repository

### PR DESCRIPTION
**Pull request by anarcat**
So here is the properly packaged debian source. an official debian package was just uploaded for Debian unstable, and should be in the [NEW queue](https://ftp-master.debian.org/new.html) shortly. Once that process is passed, the package will officially be in Debian and will eventually be part of the next stable release as well. The [RFP](https://bugs.debian.org/638422) should also be automatically closed then.

While debian packages sources are usually maintained inside the debian infrastructure (for example, in [collab-maint](https://wiki.debian.org/Teams/CollabMaint)), i wanted to give you an opportunity to see how i have built the debian package here, and eventually to take over maintainership yourself, if you are interested. I have mostly followed the [debmake guide](https://www.debian.org/doc/manuals/debmake-doc/) i have mentionned earlier. I have also copied stuff from the `.deb` you have produced earlier.

The result is this pull request: everything is in the `debian/` subdirectory. I have also filed issues #12, #13, #14 and #15 here that pertain to some improvements that could be done to the upstream source so that things would make a little more sense.

At this point, the package is *not* a "[native package](https://wiki.debian.org/DebianMentorsFaq#What_is_the_difference_between_a_native_Debian_package_and_a_non-native_package.3F)", that is: there is a `-1` in the debian version to show that the maintainer is *not* upstream. If you *do* merge this pull request however, you may start to build a native package yourself and upload it directly into debian yourself. To upload the package, you would need a [mentor](https://wiki.debian.org/DebianMentors) like myself until you become a [Debian maintainer](https://wiki.debian.org/DebianMaintainer) or [Debian developer](https://wiki.debian.org/DebianDeveloper).

If you do not wish to manage the package yourself, i recommend that you do *NOT* merge this pull request. In that case, I will simply maintain a "debian" branch in the debian infrastructure and maintain the package myself until you wish to do it yourself (if ever).

I hope this is clear enough, let me know if you have any questions of course!

### CODE REVIEW

**Comment by rfrail3** [comment]
I am very grateful to see this job. Don't doub that I don't lose this oportunity.

The merge is done, I wish to manage the package myself if you cover it with your mentor position.

I will work in the opened issues, we are in touch.

Thanks!

**Comment by anarcat** [comment]
i'm happy to hear that! i'll be glad to hand over the package to you once you provide patches to that regard.

you will probably want to add Vcs fields to the package, by the way.. https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-VCS-fields

thanks for merging! :)

**Comment by anarcat** [comment]
tuptime was accepted into debian! https://tracker.debian.org/pkg/tuptime

**Comment by rfrail3** [comment]
Great!!

**Pull request merged**
