### PR TITLE
Parameter --since, displays uptime since the given timestamp

### PR DESCRIPTION
**Pull request by relet**
I needed a way do display uptime since a given event (e.g. uptime since the last successful test run). This is implemented here with the parameter --since (-S). Sending this pull request in case you find it useful.

The current version only displays the value (human readable or in seconds, depending on the -s parameter), but feel free to integrate in into the verbose output.

### CODE REVIEW

**Comment by rfrail3** [comment]
Hi relet,

Please, check the last commit in dev branch "468094b229d508d45715c7bad4d940d9f1bd5eca", there are available since/until options for narrow between startup/downtime registers and/or between timestamps.

Regards,

**Comment by relet** [comment]
Hi Ricardo -

It seems to work, as far as I can tell.

This one should be possible to fix, I think:
# ./tuptime -s --tsince $(($(date +%s) - 1000)) --tuntil $(($(date +%s) -
500))
WARNING:root:Option "tuntil" higher or equal than last startup timestamp +
uptime + downtime timestamp timestamp: 1013 - Not applying.

I tested a bit around my use case. I think it is missing a structured
output for the default uptime data. That is, something easy to parse (JSON,
TSV, table view?).
If I want to know my system uptime since the given timestamp, I need to
read the last value in the line "System uptime:". The current table view
does not work, since it does not add up the uptimes.

Cheers,
Thomas

**Comment by rfrail3** [comment]
Hi Thomas,


Thanks, you reach a corner case. In this situation, as the matching row
don't have a valid timestamp startup, because is narrow before with
--tisince, is not possible to calculate the uptime, well it would be
possible, but it's too hacky because the code design didn't have in focus
this type of tiny reports.

I am thinking on merge this functionality into master but I don't know if
--tsince and --tuntil are good enought options for pass. In cases like this
one, without a valid startup, is not possible to cut the time under
shutdown timestamp.

Good to know you opinion on an easy to parse report. It is possible to
include it in a future release.

Please, can you tell me the case when the table view didn't work?.


Thanks,

2016-02-29 12:44 GMT+01:00 Thomas Hirsch <notifications@github.com>:

**Comment by rfrail3** [comment]
Hi Thomas,

Sorry but I was thinking the problem in the wrong way. Please, check the
last dev commit, your command example works ok. Please, let me know if you
have any issue.

Thanks,

2016-02-29 14:47 GMT+01:00 Ricardo Fraile <ricardo.fraile@gmail.com>:

**Comment by relet** [comment]
That works nicely. :)

Here are more corner cases:
# ./tuptime -s --tsince $(($(date +%s) - 5001000)) --tuntil $(($(date +%s)
- 5000500))
WARNING:root:Option "tuntil" lower than first startup timestamp. 1455008745
- Not applying.
WARNING:root:Option "tsince" lower or equal than first startup timestamp:
1455008745 - Not applying.

IMHO, the expected behaviour would be to apply the timestamp (you may still
print a warning if you like), but return zero uptime. If the system was not
up at that time, tuptime should return zero.
Otherwise, any script that uses tuptime would have to handle corner cases
individually, because the behaviour changes.

I haven't looked at the code yet. Can you tell where these twelve seconds
in "System uptime" are coming from:
# ./tuptime -s --tsince $(($(date +%s) - 1000))
System startups: 1   since   1456814531
System shutdowns: 0 ok   -   0 bad
System uptime: 100.0 %   -   1012.93


What I mean by structured data, would be anything that I can quickly pipe
into another command to retrieve the field I need. The modern choice might
be JSON, then when you have an output like {"uptime": {"seconds":
1116272.36, "percent": 61.78}} you can do tuptime [params] | jq
.uptime.seconds
Or you could use pyjq and allow the user to query the output directly.

Other options would be comma separated values or tab separated values. Then
it doesn't even have to be that different from what you have now.

**Comment by rfrail3** [comment]
Yes, you are right. Please, check the last commit.

My bet for the difference in the system uptime is because it is a virtual
server or it have ntp and when it was started, the time isn't correctly. Is
it?

Thanks for the tips for the structured data output. I take note.


2016-03-01 8:10 GMT+01:00 Thomas Hirsch <notifications@github.com>:

**Comment by rfrail3** [comment]
Hi relet,

Did you tried something?

I'm still interested in your 12 seconds drift, you are running in a server with ntp or similar? Please, can you provide me more information.

Fianlly I added a csv report to the outputs. I discard xml and json for avoid load an other module.

Thanks,

**Comment by relet** [comment]
Sorry, I got distracted a bit by work. ;)
I think what you say is probable. The machines I tested this on are running
ntpd, but they have long downtimes of ~10h at night. I will keep you
updated with what I observe.

**Comment by rfrail3** [comment]
Ok, if it happends again, please, give me the output of this commands:

::~$ cat /proc/stat | grep btime
btime 1457527859
:~$ tuptime -ts -S-1
No.   Startup Date    Uptime   Shutdown Date   End   Downtime

162     1457527862   4377.68

Note that, there is a 3 seconds offset. This case is in a laptop switched
off a few days, the ntp syncing the clock after tuptime detect and register
the new startup:

:~$ tuptime -s --tsince $(($(date +%s) - 1000))
System startups: 1   since   1457531390
System shutdowns: 0 ok   -   0 bad
System uptime: 100.0 %   -   1002.62
System downtime: 0.0 %   -   0
System life: 1002.62

Thanks,


2016-03-09 14:43 GMT+01:00 Thomas Hirsch <notifications@github.com>:

**Pull request closed without merging**
